# Generated by Django 6.0.1 on 2026-01-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('service_categories', models.JSONField(blank=True, default=list)),
                ('service_area', models.TextField(help_text='Cities, neighborhoods, ZIP codes you serve')),
                ('licensed_and_insured', models.BooleanField(default=False)),
                ('license_insurance_notes', models.TextField(blank=True)),
                ('best_time_to_contact', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('years_in_business', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
